---
title: "Exploration of raw data"
author: "Rebecca Barter"
date: "7/18/2018"
output:
  html_document:
    toc: true
    number_sections: true
---

```{r echo = FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(lubridate)
library(knitr)
library(gt)
library(data.table)
## devtools::install_github("rlbarter/superheat")
library(superheat)
library(bit64)
```

```{r echo = FALSE, message=FALSE, warning=FALSE}
# load raw data
organs <- read_csv("../../data/raw_data/global-organ-donation.csv")
```

# Missing values

The distribution of missing values is shown in the heatmap below.

```{r heatmap, echo = FALSE, fig.height = 10, fig.width=12, fig.align='center', fig.cap = "A heatmap showing the extend of missingness in the data. A grey entry in the heatmap corresponds to a non-missing entry in the data, while a white entry in the heatmap corresponds to a missing entry in the data. The year is reported on the left of the heatmap."}
organs %>% map_df(~ as.numeric(!is.na(.x))) %>%
  as.matrix %>%
  superheat(heat.pal = c("white", "grey40"),
            membership.rows = organs$REPORTYEAR,
            grid.hline.col = "grey90",
            grid.vline.col = "grey90",
            bottom.label.col = "white",
            left.label.col = "white",
            bottom.label.text.angle = 90,
            legend = FALSE)
```

The following countries are the only countries that have all 18 years of deceased donor counts:

```{r echo = FALSE}
organs %>%
  group_by(COUNTRY) %>%
  summarise(complete_data = sum(!is.na(`TOTAL Actual DD`)) == 18) %>%
  filter(complete_data) %>%
  select(`Countries with complete data` = COUNTRY) %>%
  arrange(`Countries with complete data`)  %>%
  gt
```

# Comparing countries



