---
title: "Exploring models of the organs data"
author: "Rebecca Barter"
date: "03/05/2019"
output:
  html_document:
    toc: true
    number_sections: true
---


In this file, we summarise the modeling approaches, and summarise their results.

Our goal was to predict the number of organ donations using the year and population. We fit two models (1) a linear regression model, and (2) a random forest model.

```{r echo = FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
model_results <- read_csv("../../data/results/model_results.csv")
```


The plot below shows the predicted vs actual values for each model

```{r echo = FALSE, fig.align = "center"}
model_results %>%
  ggplot(aes(x = true_dd, y = lm_fitted_dd, col = region)) +
  geom_point(alpha = 0.5) +
  theme_classic() +
  ggtitle("Linear model results vs truth")
model_results %>%
  ggplot(aes(x = true_dd, y = rf_fitted_dd, col = region)) +
  geom_point(alpha = 0.5) +
  theme_classic() +
  ggtitle("Linear model results vs truth")
```

Discuss some interesting things about the model results.